services:
  mysql:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: volunteer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: changeme
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: changeme
    ports:
      - "8080:80"
volumes:
  mysql_data: